# Generated by Django 4.2.15 on 2024-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_discount_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
